"""Initial_migration

Revision ID: 0eb22388b1d4
Revises: 
Create Date: 2026-01-16 13:35:35.147435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb22388b1d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('WORKSHOP', 'HACKATHON', 'SEMINAR', 'BOOTCAMP', 'LECTURE', name='eventtype'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hackathon_teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_name', sa.String(length=200), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_name', 'team_name', name='unique_event_team_name')
    )
    op.create_index(op.f('ix_hackathon_teams_event_name'), 'hackathon_teams', ['event_name'], unique=False)
    op.create_index(op.f('ix_hackathon_teams_team_name'), 'hackathon_teams', ['team_name'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='resourcelevel'), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_url')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('registrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('operative_name', sa.String(length=100), nullable=False),
    sa.Column('moodle_id', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'moodle_id', name='unique_event_moodle')
    )
    op.create_index(op.f('ix_registrations_moodle_id'), 'registrations', ['moodle_id'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('moodle_id', sa.String(length=20), nullable=False),
    sa.Column('roll_no', sa.String(length=20), nullable=False),
    sa.Column('division', sa.String(length=5), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('year', sa.String(length=10), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('is_leader', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['hackathon_teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_email'), 'team_members', ['email'], unique=False)
    op.create_index(op.f('ix_team_members_moodle_id'), 'team_members', ['moodle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_members_moodle_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_email'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_registrations_moodle_id'), table_name='registrations')
    op.drop_table('registrations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('resources')
    op.drop_index(op.f('ix_hackathon_teams_team_name'), table_name='hackathon_teams')
    op.drop_index(op.f('ix_hackathon_teams_event_name'), table_name='hackathon_teams')
    op.drop_table('hackathon_teams')
    op.drop_table('events')
    # ### end Alembic commands ###
